knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(GOOGLE_CLIENT_ID)%'
            client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
            redirect_route: connect_google_check
            redirect_params: {}
        azure:
            type: azure
            client_id: '%env(AZURE_CLIENT_ID)%'
            client_secret: '%env(AZURE_CLIENT_SECRET)%'
            redirect_route: app_tool_oauth_microsoft_callback
            redirect_params: {}
            tenant: '%env(AZURE_TENANT_ID)%'
            api_version: 'v2.0'
            url_api: 'https://graph.microsoft.com/'
            default_end_point_version: '1.0'
        azure_sap_c4c:
            type: azure
            client_id: '%env(AZURE_CLIENT_ID)%'
            client_secret: '%env(AZURE_CLIENT_SECRET)%'
            redirect_route: app_tool_oauth_sap_c4c_callback
            redirect_params: {}
            tenant: '%env(AZURE_TENANT_ID)%'
            api_version: 'v2.0'
        azure_sap_sac:
            type: azure
            client_id: '%env(AZURE_CLIENT_ID)%'
            client_secret: '%env(AZURE_CLIENT_SECRET)%'
            redirect_route: app_tool_oauth_sap_sac_callback
            redirect_params: {}
            tenant: '%env(AZURE_TENANT_ID)%'
            api_version: 'v2.0'
        hubspot:
            type: generic
            provider_class: '\HelpScout\OAuth2\Client\Provider\HubSpot'
            client_id: '%env(HUBSPOT_CLIENT_ID)%'
            client_secret: '%env(HUBSPOT_CLIENT_SECRET)%'
            redirect_route: app_tool_oauth_hubspot_callback
            redirect_params: {}
        wrike:
            type: generic
            provider_class: 'App\OAuth2\WrikeProvider'
            client_id: '%env(WRIKE_CLIENT_ID)%'
            client_secret: '%env(WRIKE_CLIENT_SECRET)%'
            redirect_route: app_tool_oauth_wrike_callback
            redirect_params: {}