knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(GOOGLE_CLIENT_ID)%'
            client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
            redirect_route: connect_google_check
            redirect_params: {}
        azure:
            type: azure
            client_id: '%env(AZURE_CLIENT_ID)%'
            client_secret: '%env(AZURE_CLIENT_SECRET)%'
            redirect_route: connect_microsoft_check
            redirect_params: {}
            tenant: '%env(AZURE_TENANT_ID)%'
            api_version: 'v2.0'
            url_api: 'https://graph.microsoft.com/'
            default_end_point_version: '1.0'