security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        prompt_api:
            pattern: ^/api/prompts
            stateless: true
            custom_authenticators:
                - App\Security\PromptApiTokenAuthenticator

        mcp_api:
            pattern: ^/api/mcp
            stateless: true
            custom_authenticators:
                - App\Security\PromptApiTokenAuthenticator

        api:
            pattern: ^/api
            stateless: true
            jwt: ~
            custom_authenticators:
                - App\Security\TestAuthenticator
        
        main:
            lazy: true
            provider: app_user_provider
            entry_point: App\Security\AuthenticationEntryPoint
            logout:
                path: app_logout
            custom_authenticators:
                - App\Security\GoogleAuthenticator
                - App\Security\TestAuthenticator
                - App\Security\MagicLinkAuthenticator
            access_denied_handler: App\Security\AccessDeniedHandler
    
    access_control:
        - { path: ^/api/mcp, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/prompts, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/integration, roles: PUBLIC_ACCESS }
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/skills, roles: PUBLIC_ACCESS }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_USER }
        - { path: ^/auth, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/waitlist, roles: PUBLIC_ACCESS }
        - { path: '^/[a-f0-9\-]+/file/', roles: PUBLIC_ACCESS }
        - { route: app_home, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10