parameters:
    locale: '%env(APP_LOCALE)%'
    app.supported_locales: '%env(csv:APP_LOCALES)%'
    app.url: '%env(APP_URL)%'
    app.api_auth_user: '%env(API_AUTH_USER)%'
    app.api_auth_password: '%env(API_AUTH_PASSWORD)%'
    app.encryption_key: '%env(ENCRYPTION_KEY)%'
    minio.endpoint: '%env(MINIO_ENDPOINT)%'
    minio.root_user: '%env(MINIO_ROOT_USER)%'
    minio.root_password: '%env(MINIO_ROOT_PASSWORD)%'
    minio.bucket: '%env(MINIO_BUCKET)%'
    minio.public_bucket: '%env(MINIO_PUBLIC_BUCKET)%'
    minio.region: '%env(MINIO_REGION)%'
    minio.use_path_style: '%env(bool:MINIO_USE_PATH_STYLE)%'
    azure_client_id: '%env(AZURE_CLIENT_ID)%'
    azure_client_secret: '%env(AZURE_CLIENT_SECRET)%'
    azure_tenant_id: '%env(AZURE_TENANT_ID)%'

imports:
    - { resource: services/integrations.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Integration/SystemTools/'
            - '../src/Integration/UserIntegrations/'
            - '../src/Service/Integration/AtlassianOAuthService.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
    
    App\Controller\IntegrationApiController:
        arguments:
            $apiAuthUser: '%app.api_auth_user%'
            $apiAuthPassword: '%app.api_auth_password%'

    App\Controller\SkillsApiController:
        arguments:
            $apiAuthUser: '%app.api_auth_user%'
            $apiAuthPassword: '%app.api_auth_password%'

    App\Security\TestAuthenticator:
        arguments:
            $environment: '%kernel.environment%'
    
    App\Service\MagicLinkService:
        arguments:
            $magicLinkSecret: '%env(MAGIC_LINK_SECRET)%'
    
    App\Security\MagicLinkAuthenticator:
        arguments:
            $userRepository: '@App\Repository\UserRepository'
            $userRegistrationService: '@App\Service\UserRegistrationService'
            $magicLinkService: '@App\Service\MagicLinkService'
            $auditLogService: '@App\Service\AuditLogService'
            $router: '@router'
            $logger: '@logger'

    App\Controller\RegisterApiController:
        arguments:
            $apiAuthUser: '%env(API_AUTH_USER)%'
            $apiAuthPassword: '%env(API_AUTH_PASSWORD)%'

    App\EventListener\TokenRefreshSubscriber:
        arguments:
            $container: !service_locator
                knpu.oauth2.registry: '@knpu.oauth2.registry'